package org.nyusziful.Main;

import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.nyusziful.pictureorganizer.DAL.DAO.MediaFileVersionDAOImplHib;
import org.nyusziful.pictureorganizer.DAL.Entity.MediaFileVersion;
import org.nyusziful.pictureorganizer.DAL.JPAConnection;
import org.nyusziful.pictureorganizer.Service.Hash.JPGHash;
import org.nyusziful.pictureorganizer.Service.Hash.JPEGMediaFileStruct;
import org.nyusziful.pictureorganizer.Service.Hash.JPEGSegment;
import org.nyusziful.pictureorganizer.Service.Hash.MediaFileHash;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Set;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.*;

/**
 * Integration test: copies a plain JPEG into a watched folder, verifies the
 * watch service detects the missing-import conditions, performs a manual import,
 * and checks that only the COMMENT segment of the file was changed.
 *
 * <p>Uses an in-memory H2 database (h2-picture persistence unit) so that no
 * external MySQL server is required.  The schema is auto-generated by Hibernate
 * from the entity annotations ({@code hibernate.hbm2ddl.auto=create-drop}).
 */
public class FolderWatchImportTest {

    private static final String TEST_JPG = "DSC08806.jpg";
    private static final long WATCH_TIMEOUT_SEC = 10;

    private Path tempDir;
    private MediaFileVersionDAOImplHib dao;
    private FolderWatchService watcher;

    private static class FileEvent {
        final File file;
        final Set<FolderWatchService.FileStatus> status;
        FileEvent(File file, Set<FolderWatchService.FileStatus> status) {
            this.file = file;
            this.status = status;
        }
    }
    private final BlockingQueue<FileEvent> events = new LinkedBlockingQueue<>();

    @Before
    public void setUp() throws Exception {
        // Must set TEST mode before the first getInstance() call so that JPAConnection
        // uses the h2-picture persistence unit instead of trying to reach MySQL.
        JPAConnection.shutdown();
        JPAConnection.resetInstance();
        JPAConnection.setMode(JPAConnection.DBMode.TEST);

        dao = new MediaFileVersionDAOImplHib();

        HashChecker checker = hash -> dao.getMediafileVersionByFileHash(hash) != null;

        tempDir = Files.createTempDirectory("pictureImportTest_");
        watcher = new FolderWatchService(tempDir, checker);
        watcher.setFileEventListener((file, status) -> events.offer(new FileEvent(file, status)));
        watcher.start();
    }

    @After
    public void tearDown() throws Exception {
        if (watcher != null) watcher.stop();
        JPAConnection.shutdown();
        JPAConnection.resetInstance();
        JPAConnection.setMode(JPAConnection.DBMode.PROD); // restore default for any subsequent tests
        if (tempDir != null) FileUtils.deleteDirectory(tempDir.toFile());
    }

    @Test
    public void testNewJpgImportScenario() throws Exception {

        // ── 1. Copy a pure JPEG (no hash, no backup) into the watched folder ──────

        File sourceJpg = new File(getClass().getClassLoader().getResource(TEST_JPG).getFile());
        Path destPath = tempDir.resolve(TEST_JPG);
        Files.copy(sourceJpg.toPath(), destPath, StandardCopyOption.REPLACE_EXISTING);
        File destJpg = destPath.toFile();

        // ── 2. Wait for the watch service to detect the file ─────────────────────

        FileEvent event = events.poll(WATCH_TIMEOUT_SEC, TimeUnit.SECONDS);
        assertNotNull("Watch service did not detect the new file within timeout", event);
        assertEquals("Event file path mismatch", destJpg.getCanonicalPath(), event.file.getCanonicalPath());

        // ── 3. Verify the detected conditions ────────────────────────────────────

        // (a) Not in DB
        assertTrue("Expected NOT_IN_DB status",
                event.status.contains(FolderWatchService.FileStatus.NOT_IN_DB));

        String canonicalHash = MediaFileHash.getHash(destJpg).hash;
        assertNotNull("Canonical hash must not be null for a valid JPEG", canonicalHash);
        assertNotEquals("Source JPEG must be a readable JPEG with media data",
                MediaFileHash.EMPTYHASH, canonicalHash);
        assertNull("File should not be in DB yet", dao.getMediafileVersionByFileHash(canonicalHash));

        // (b) EXIF backup missing
        assertTrue("Expected EXIF_BACKUP_MISSING status",
                event.status.contains(FolderWatchService.FileStatus.EXIF_BACKUP_MISSING));
        File bakFile = new File(destJpg.getPath() + ".bak");
        assertFalse("Backup file must not exist yet", bakFile.exists());

        // (c) Canonical hash not yet embedded
        assertTrue("Expected HASH_MISSING status",
                event.status.contains(FolderWatchService.FileStatus.HASH_MISSING));
        assertFalse("File must not have embedded hash yet", JPGHash.hasCanonicalHash(destJpg));

        // ── 4. Pause the watcher during maintenance ───────────────────────────────

        watcher.pause();
        assertTrue("Watcher should be paused", watcher.isPaused());

        // ── 5. Manual import ──────────────────────────────────────────────────────

        ImportService importService = new ImportService();

        // (a) Write history to DB with canonical hash
        importService.writeHistory(destJpg, canonicalHash);
        MediaFileVersion record = dao.getMediafileVersionByFileHash(canonicalHash);
        assertNotNull("History record must be persisted in DB", record);
        assertEquals("Persisted hash must match canonical hash", canonicalHash, record.getFilehash());

        // (b) Create EXIF backup
        assertTrue("ExifBackup creation must succeed", importService.createExifBackup(destJpg));
        assertTrue("Backup file must exist after creation", bakFile.exists());

        // Capture the file state AFTER the backup step but BEFORE hash embedding.
        // addBackupExif modifies the file in-place, so we take our "before" snapshot here
        // to verify that writeCanonicalHashToFile adds only the COMMENT segment.
        byte[] originalBytes = Files.readAllBytes(destPath);
        JPEGMediaFileStruct originalStruct = JPGHash.scan(destJpg);

        // (c) Write canonical hash to the JPEG file
        assertTrue("Writing canonical hash must succeed",
                importService.writeCanonicalHashToFile(destJpg, canonicalHash));

        // ── 6. Verify file integrity before re-enabling the watcher ───────────────

        byte[] modifiedBytes = Files.readAllBytes(destPath);

        // The canonical (media-data) hash must be unchanged — only metadata was modified
        String hashAfter = importService.computeCanonicalHash(destJpg);
        assertEquals("Canonical hash must be unchanged after embedding", canonicalHash, hashAfter);

        // The embedded hash must be readable and correct
        String embeddedHash = importService.readCanonicalHashFromFile(destJpg);
        assertEquals("Embedded hash must match canonical hash", canonicalHash, embeddedHash);

        // The only structural difference must be the new COMMENT segment
        assertOnlyCommentAdded(originalBytes, originalStruct, modifiedBytes, destJpg, canonicalHash);

        // Drain any events that might have been queued while we were paused
        assertTrue("No unexpected events should have been delivered while paused",
                events.isEmpty());

        // ── 7. Re-enable the watcher ──────────────────────────────────────────────

        watcher.resume();
        assertFalse("Watcher should no longer be paused", watcher.isPaused());
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Asserts that the only difference between {@code originalBytes} and
     * {@code modifiedBytes} is the insertion of a single COMMENT segment
     * immediately after the SOI, containing the expected canonical hash.
     */
    private static void assertOnlyCommentAdded(
            byte[] originalBytes,
            JPEGMediaFileStruct originalStruct,
            byte[] modifiedBytes,
            File modifiedFile,
            String canonicalHash) throws IOException {

        // Modified file must be LARGER (new COMMENT segment was added)
        assertTrue("Modified file must be larger than original",
                modifiedBytes.length > originalBytes.length);

        // Scan the modified JPEG structure
        JPEGMediaFileStruct modifiedStruct = JPGHash.scan(modifiedFile);
        List<JPEGSegment> origSegs = originalStruct.getSegments();
        List<JPEGSegment> modSegs = modifiedStruct.getSegments();

        // Exactly one new segment (the COMMENT) was inserted
        assertEquals("Modified JPEG should have exactly one more segment than original",
                origSegs.size() + 1, modSegs.size());

        // The new segment must be a COMMENT (0xFE = 254)
        JPEGSegment commentSeg = null;
        for (JPEGSegment seg : modSegs) {
            if (seg.getMarker() == 0xFE) {
                commentSeg = seg;
                break;
            }
        }
        assertNotNull("Modified JPEG must contain a COMMENT segment", commentSeg);

        // SOI (2 bytes) of both files must be identical
        assertEquals("SOI first byte",  originalBytes[0], modifiedBytes[0]);
        assertEquals("SOI second byte", originalBytes[1], modifiedBytes[1]);

        // Bytes after the COMMENT segment in the modified file must match
        // the bytes after SOI in the original file — i.e., the rest is untouched.
        int commentEnd = (int)(commentSeg.getStartAddress() + commentSeg.getLength());
        int originalOffset = 2; // skip SOI
        int modifiedOffset  = commentEnd; // skip SOI + COMMENT

        assertEquals("Tail length mismatch: modified file length unexpected",
                originalBytes.length - originalOffset,
                modifiedBytes.length - modifiedOffset);

        int tailLength = originalBytes.length - originalOffset;
        for (int i = 0; i < tailLength; i++) {
            assertEquals("Byte at tail position " + i + " (orig offset " + (originalOffset + i) +
                            ", mod offset " + (modifiedOffset + i) + ") must be unchanged",
                    originalBytes[originalOffset + i],
                    modifiedBytes[modifiedOffset + i]);
        }
    }
}
